ncxmod: lookup current user's uid if home directory is unknown
In ncxmod_get_userhome(), if the username is NULL, search the password
file by the current user's effective UID before falling back to the
default path.  This avoids the following error when the $HOME environment
variable is not set:

Error: invalid user name in path string (~/.yuma/startup-cfg.xml)